version: '3'
services:
  faythe:
    build: .
    ports:
      - 8600:8600
    volumes:
      - ./examples/faythe.yml:/etc/faythe/config.yml

  etcd:
    image: bitnami/etcd:3
    environment:
      - ALLOW_NONE_AUTHENTICATION=yes
    ports:
      - 2379:2379
      - 2380:2380
    volumes:
      - etcd_data:/binami


volumes:
  etcd_data:
    driver: local
