# OpenStackConfiguration.
openstack_configs:
  openstack-1f:
    region_name: "RegionOne"
    domain_name: "Default"
    auth_url: "http://openstackhost1:5000"
    username: "admin"
    password: "password"
    project_name: "tenantName"
    stack_query:
      update_interval: 30s
      list_opts:
        tags: "scale"

  openstack-2f:
    region_name: "RegionOne"
    domain_name: "Default"
    auth_url: "http://openstackhost2:5000"
    username: "admin"
    password: "password"
    project_name: "tenantName"
    stack_query:
      update_interval: 30s
      list_opts:
        tags: "scale"

# StackStormConfiguration
stackstorm_configs:
  stackstorm-1f:
    host: "stackstormhost1"
    api_key: "fakestackstomrapikey"
    limit_num_alerts: 5

  stackstorm-2f:
    host: "stackstormhost2"
    api_key: "fakestackstomrapikey"
    limit_num_alerts: 5

server_config:
  # Example:
  # "www.example.com"
  # "([a-z]+).domain.com"
  remote_host_pattern: "192.168.(128|129).*"
  basic_auth:
    username: "admin"
    password: "notverysecurepassword"
  log_dir: "/tmp/faythe-logs"
