# OpenStackConfiguration.
# These configs will be overwritten by OS_* environment variables.
# Check handlers/openstack/.env.example for details.
openstack:
  regionName: "RegionOne"
  domainName: "Default"
  authURL: "http://openstackhost:5000"
  username: "admin"
  password: "password"
  projectName: "tenantName"
  stackQuery:
    updateInterval: 30
    listOpts:
      tags: "scale"

# StackStormConfiguration
# These configs will be overwritten by STACKSTORM_* environment variables.
# Check handlers/stackstorm/.env.example for details.
stackstorm:
  host: "stackstormhost"
  apiKey: "fakestackstomrapikey"

server:
  # Example:
  # "www.example.com"
  # "([a-z]+).domain.com"
  remoteHostPattern: "192.168.(128|129).*"
  basicAuth:
    username: "admin"
    password: "notverysecurepassword"
