openstack:
  regionName: "RegionOne"
  domainName: "Default"
  domainId: "domainId"
  authURL: "http://openstackhost:5000"
  username: "admin"
  password: "password"
  projectId: "tenantID"
  projectName: "tenantName"
  stackTags: "scale"
  updateInterval: 30

stackstorm:
  host: "stackstormhost"
  apiKey: "fakestackstomrapikey"
