openstack:
  regionName: "RegionOne"
  domainName: "Default"
  authURL: "http://openstackhost:5000"
  username: "admin"
  password: "password"
  projectID: "tenantID"
  projectName: "tenantName"
  stackTags: "scale"
  updateInterval: 30

stackstorm:
  host: "stackstormhost"
  rule: "test-rule"
  apiKey: "fakestackstomrapikey"
